// Auth
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// Flash Notify
export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
export const REMOVE_FLASH_MESSAGE = "REMOVE_FLASH_MESSAGE";

// Groups
export const GROUPS_START = "GROUPS_START";
export const GROUPS_SUCCESS = "GROUPS_SUCCESS";
export const SET_GROUP = "SET_GROUP";
export const START_GROUP_MEMBERS = "START_GROUP_MEMBERS";
export const SUCCESS_GROUP_MEMBERS = "SUCCESS_GROUP_MEMBERS";

// Tasks
export const GROUP_TASKS_START = "GROUP_TASKS_START";
export const GROUP_TASKS_SUCCESS = "GROUP_TASKS_SUCCESS";
export const TASK_START = "TASK_START";
export const TASK_SUCCESS = "TASK_SUCCESS";
export const TASK_MEMBERS_START = "TASK_MEMBERS_START";
export const TASK_MEMBERS_SUCCESS = "TASK_MEMBERS_SUCCESS";
export const TASKS_START = "TASKS_START";
export const TASKS_SUCCESS = "TASKS_SUCCESS";

// Notifications
export const NOTIFICATION_START = "NOTIFICATION_START";
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";

// Users
export const USER_START = "USER_START";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILED = "USER_FAILED";
